CREATE TABLE users (id SERIAL PRIMARY KEY, username TEXT UNIQUE, password TEXT, role TEXT);
CREATE TABLE threads (id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES users ON DELETE CASCADE, subject TEXT UNIQUE);
CREATE TABLE messages (id SERIAL PRIMARY KEY, thread_id INTEGER REFERENCES threads ON DELETE CASCADE, content TEXT, created_at TIMESTAMP, username TEXT);